### ISSUE TITLE
Store should only store one state per turn number

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1554] opened 2020-04-24 20:53 UTC
https://github.com/statechannels/monorepo/issues/1555 asserts that the store should only support one state per turn number, within a given channel.

The store has no control over what state a peer sends for turn `n`. If one of my workflows subsequently want to support a different state at turn `n`, what should the store do?

Right now, some store logic depends (might depend?) on the fact that there's only one state per turn number.

See https://github.com/statechannels/monorepo/issues/1456#issuecomment-615520101

**Comment by lalexgap** [comment] 2020-04-29 16:47
Duplicate of #1555

**Comment by andrewgordstewart** [comment] 2020-04-29 17:11
This is similar to, but not _exactly_ a duplicate 😛 I'll edit the description to make it more clear.

**Comment by lalexgap** [comment] 2020-05-07 23:19
I think we ran into this with #1729 where the `store` accepts a state from `pushMessage` without checking that a state with the same turn number has been added.

**Comment by lalexgap** [comment] 2020-05-08 17:42
I think for the immediate future we should throw an error if the `store` receives a state with the same turn number. @andrewgordstewart  does that sound good to you?

**Closed** 2020-05-09 15:51 UTC
Labels: bug
