### ISSUE TITLE
Flickering integration test (spent != -earned)

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#1525] opened 2020-04-22 22:27 UTC
The part of the integration test checking spent vs earned was [re-enabled yesterday](https://github.com/statechannels/monorepo/pull/1492/commits/67be3ce7baa57f3b509366b3d410491fa32335f4).

During this [test run](https://app.circleci.com/pipelines/github/statechannels/monorepo/5392/workflows/f6f7af9e-2352-493b-baef-3cb8704a5fb0/jobs/20279), one of these expectations failed. The test run did not involve any meaningful change, since the Dexie backend was not used by the wallet.

**Comment by lalexgap** [comment] 2020-04-29 17:27
I suspect that this could be caused by the fact that we're not using a unique file name when running the tests. That would mean that if other tests are running concurrently they could connect to the same torrent and download, causing the seeder to earn additional funds.

**Comment by lalexgap** [comment] 2020-04-29 17:36
Another flicker: https://app.circleci.com/pipelines/github/statechannels/monorepo/5653/workflows/173952a2-761d-463a-a9b2-d4d9c6574643/jobs/21864/steps

**Comment by andrewgordstewart** [comment] 2020-04-29 18:01
> I suspect that this could be caused by the fact that we're not using a unique file name when running the tests. That would mean that if other tests are running concurrently they could connect to the same torrent and download, causing the seeder to earn additional funds.

Are the trackers not sandboxed to the circle machine?

**Comment by andrewgordstewart** [comment] 2020-04-29 19:19
Another possible cause -- the leecher and the seeder end up with a different outcome on their last state, because of something like [this](https://github.com/statechannels/monorepo/issues/1456#issuecomment-615520101)

**Comment by lalexgap** [comment] 2020-04-29 19:26
> > I suspect that this could be caused by the fact that we're not using a unique file name when running the tests. That would mean that if other tests are running concurrently they could connect to the same torrent and download, causing the seeder to earn additional funds.
> 
> Are the trackers not sandboxed to the circle machine?

I think you're correct. I think previously we were using public trackers (a long time ago) so I assumed that that was the case, but it looks like we're spinning up our own tracker which I expect would be sandboxed to the machine.

I also made a change to use unique file names and ran into this error again right after, so that pretty concretely rules out my theory.

**Comment by lalexgap** [comment] 2020-05-04 17:36
This may have been resolved with the recent changes. Leaving open for now.

**Comment by lalexgap** [comment] 2020-05-07 04:43
> This may have been resolved with the recent changes. Leaving open for now.

Closing as it has not reappeared.

**Closed by lalexgap** 2020-05-07 04:43 UTC
Labels: flickering, package: web3torrent, package: xstate-wallet
