### ISSUE TITLE
Switching address and returning to the app does not work

### ISSUE THREAD

**Issue by lalexgap** [statechannels/monorepo#2128] opened 2020-06-10 17:23 UTC
If you
- Use web3torrent with one address
- Close web3torrent
- Switch address
- navigate to web3torrent and try to use it

it doesn't seem to work

**Comment by andrewgordstewart** [comment] 2020-06-11 18:07
@snario this is a duplicate of https://github.com/statechannels/monorepo/issues/2126. Should we close this, and add the relevant context to 2126?

**Closed** 2020-06-15 16:45 UTC
Labels: package: web3torrent
