### ISSUE TITLE
Domain Budget warning

### ISSUE THREAD

**Issue by kerzhner** [statechannels/monorepo#2131] opened 2020-06-10 18:15 UTC
This happens locally when roloading the file page with an existing budget.
```
index.js:1472 Warning: Failed prop type: The prop `title` is marked as required in `ForwardRef(Tooltip)`, but its value is `null`.
    in ForwardRef(Tooltip) (created by WithStyles(ForwardRef(Tooltip)))
    in WithStyles(ForwardRef(Tooltip)) (at DomainBudget.tsx:137)
    in div (at DomainBudget.tsx:136)
    in div (at DomainBudget.tsx:100)
    in td (at DomainBudget.tsx:99)
    in tr (at DomainBudget.tsx:98)
    in tbody (at DomainBudget.tsx:97)
    in table (at DomainBudget.tsx:96)
    in DomainBudget (at File.tsx:120)
    in section (at File.tsx:106)
    in File (at App.tsx:98)
    in Route (at App.tsx:97)
    in Switch (at App.tsx:93)
    in main (at App.tsx:74)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:73)
    in App (at src/index.tsx:28)
```

**Comment by lalexgap** [comment] 2020-06-11 22:56
Having trouble reproducing this myself.

**Comment by geoknee** [comment] 2020-06-12 07:15
I can imagine there might have been an issue like this if you hadn't run `yarn` recently?

**Comment by geoknee** [comment] 2020-06-12 09:29
Hopefully #2156 will fix this. It might be a race condition where we try to render this component but `web3torrent.paymentChannelClient.myEthereumSelectedAddress` is not yet defined. 

I am a bit confused as to why TypeScript didn't catch this.

**Comment by geoknee** [comment] 2020-06-12 14:47
https://github.com/statechannels/monorepo/pull/2157

**Comment by geoknee** [comment] 2020-06-12 17:18
I'm going to close this because I think the issue has been dealt with by #2156. Let's reopen if it rears up again.

**Closed by geoknee** 2020-06-12 17:18 UTC
Labels: package: web3torrent
