### ISSUE TITLE
[devtools] Add Production/Ropsten contract deployment functionality

### ISSUE THREAD

**Issue by Alonski** [statechannels/monorepo#1906] opened 2020-05-19 16:56 UTC
**Problem description :confused:**
Currently, if someone wants to deploy a Smart Contract they have to do this manually. A way to do this is using Infura along with etherlime: https://etherlime.readthedocs.io/en/latest/api/deployers.html#infuraprivatekeydeployer

**Describe the solution you'd like :rocket:**
I suggest an APIs similar to the current API used in `setupGanache` that will allow someone to deploy Smart Contracts to Production or Ropsten (or another network) with ease.

The person deploying would need to pass in some local ENV vars such as PRODUCTION_NETWORK, PRIVATE_KEY, INFURA_API_KEY.

**Describe alternatives you've considered**
We don't do this and just keep deploying by hand.

**Comment by Alonski** [comment] 2020-05-21 15:15
@snario

**Comment by snario** [comment] 2020-05-21 17:10
Duplicate of #927

**Closed by snario** 2020-05-21 17:10 UTC
Labels: package: devtools
