### ISSUE TITLE
[web3torrent] Define how payments work

### ISSUE THREAD

**Issue by joelalejandro** [statechannels/monorepo#264] opened 2019-10-24 17:05 UTC
We haven't figured out how payments work in this app yet.

I'm opening this issue so we can discuss the following:

- How is the price calculated?
- What actions imply payment?
- What actions imply getting paid?

**Comment by snario** [comment] 2019-10-24 17:11
Here are the two important variables:

- Minimum price that the seeder will accept per byte per file
- Maximum price that the leecher will pay per byte per file

Thus, for some file a seeder uploads, they will set a min per byte rate.

Anytime a leecher wants to download a file, they will have a max per byte rate.

Then it operates like a market basically. The leecher will try to find seeders based on the lowest price they offer for some file that is lower than the max price they will pay for some file.

Now, the super simple version of this is to set both of these variables as the same thing. For example, $0.000005 per byte. Then, we can calculate the price of some file based on its size.

Leechers will pay the fixed per-byte rate to the seeders, and seeders will then send the byte.

**Comment by spersico** [comment] 2019-10-24 17:32
So... some issues with this:
The BitTorrent protocol, and the WebTorrent by extension, transfers files with chunks (the correct term is pieces) of data. The more pieces a file get, the slower that the download will be. We are dealing with TCP connections so if we reduce the piece size we could really affect the download speed (see [TCP Wiki](https://wiki.theory.org/index.php/BitTorrentSpecification#Peer_wire_protocol_.28TCP.29) ) and on a file bigger than a couple of megabytes, we could have a really big metadata size.

Other than that, on a file of... 10Mb, we would choke and unchoke 1million times... Taking into account that each time that a seeder chokes and unchokes a connection, and the leecher re-starts the download, is a couple of seconds (eg: 5-10 seconds), we could be talking of 1million * 5 seconds (not taking into account the messaging required to transfer currency), so... between 58 and 116 days to download a 10mb file

**Comment by snario** [comment] 2019-10-24 18:56
Ah right, so, I mean we ought to find a more reasonable chunk size. Maybe 100 Bytes. Or 1 Kb.

**Comment by spersico** [comment] 2019-10-25 18:29
Even with **1kb** chunks, a **10mb** file would take **15 to 30 hours** to download, and I'm being super optimistic. I'm not even taking into account the funds transfer, funds checking, slow connection, or the time to actually download the file data.

I think we are seeing this upside down, I believe that we should use a balance for each leecher, in which the leecher has to pay to the seeder initially X amount of money, and the seeder maintains a balance of each peer (how much that peer paid), and on each request the balance is updated (per the cost of byte). 
Then, if the balance gets to 0, or it's not enough for the chunk size, the leecher chokes the connection, and requests more funds.
[WebTorrent-ILP](https://github.com/emschwartz/webtorrent-ilp) went about it kinda like this.

To be clear, I'm not against rates, neither fixed nor variable, what I believe it's a bad idea, is the request-choke-payment-unchoke-respond cycle.

**Comment by snario** [comment] 2019-10-28 15:13
I see. Yeah you're making a good argument. It looks like this must have been similar to what WebTorrent ILP had to deal with, and their solution seems reasonable.

It ends up just being a tradeoff of the risk tolerance versus the practicality of the demo. Maybe the most amount of "extra buffer" we should allow for that gets caused by us choking and unchoking should be ~100%? That is, downloading a file with Web3Torrent should take 2x as long, but that is because you are paying per <whatever amount>Kb instead of paying all upfront?

**Comment by joelalejandro** [comment] 2019-10-28 15:21
What if we parallelize data streaming and payments? We could keep a track of how many bytes were transferred so far and instead of choking/unchoking, execute periodic payments with the accumulated fee for a given block/chunk/piece size. That way, you wouldn't be hindering data transfer speeds.

**Comment by snario** [comment] 2019-10-28 15:39
I guess it just starts to defeat the point of doing micropayments as then you'd be able to work around this by abusing the data transfer part of the system and not making payments, right?

**Comment by joelalejandro** [comment] 2019-10-28 15:50
What would an attack vector for the data transfer look like in this case? Maybe if we integrate this control into a torrent tracker of our own, extending from [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker)? Just like we extended the BT protocol with a custom extension, I'm thinking we can do something similar on a tracker level.

**Comment by spersico** [comment] 2019-10-28 15:53
> What would an attack vector for the data transfer look like in this case? Maybe if we integrate this control into a torrent tracker of our own, extending from [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker)? Just like we extended the BT protocol with a custom extension, I'm thinking we can do something similar on a tracker level.

Umm... but you end up losing the decentralized part of torrent sharing. If a central server (the tracker) is necessary for each download to be possible, you introduce another point of failure.

**Comment by joelalejandro** [comment] 2019-10-28 15:55
Well, what about extending `DHT`(https://github.com/webtorrent/bittorrent-dht) then?

**Comment by spersico** [comment] 2019-10-28 15:58
> Well, what about extending [`DHT`](https://github.com/webtorrent/bittorrent-dht) then? That would enable decentralized sharing, plus since it supports arbitrary data storage, we could keep payment records there, perhaps?

maybe, I don't know enough of how DHT works, I'll give it a read

**Comment by andrewgordstewart** [comment] 2019-10-31 12:52
I strongly recommend using the same terminology as in the bittorrent specification. A `piece` is some data that is transferred between two set peers, whose validity is verified before moving onto the next `piece`. Pieces are broken up further into smaller pieces, which are often called `chunks`.

What are the `validTransition` rules for the state channel backing Web3Torrent?

As a starting point, what are the flaws with making the state channel be a wrapper around the bittorrent protocol itself?
- If I want a particular piece, I make a `request` to buy a particular piece for a particular price. This does not change the channel outcome.
- If I've requested a piece, and you send a `piece` state, then it transfers the agreed upon price as long as the hash of the piece matches the requested hash.

If the native `keccak256` hash is used, this would cost ~100 gas per verification of a 512KB piece.

The problem with this, of course, is that the state itself cannot be transferred over the wire -- torrent clients need to break pieces up into chunks that are individually sent over the wire. But it can still work like:
1. A leecher requests a `piece`, staking some ether
2. A seeder responds with the signature of the `piece` itself
3. The seeder sends the `piece` in several chunks
4. Once all chunks are received, the leecher verifies the `piece`

At any point, the leecher is obliged to pay for a full piece, and is guaranteed to receive it on receipt of that piece, whether it be over the wire or through a challenge.

**Comment by joelalejandro** [comment] 2019-10-31 16:48
We've concluded that we'll spike out two different approaches to the payment model:

1) *Per-piece model:* the file gets split by a fixed number of pieces and the leecher will pay up-front before receiving the data chunks of that piece. To keep the download going as uninterrupted as possible, the leecher would start the payment request near the end of the current piece.

2) *Balance model:* the leecher pays a given amount of ETH, worth an amount X of data of the file. Once the balance is depleted, the leecher must pay again to continue.

**Comment by andrewgordstewart** [comment] 2019-11-01 07:51
I wrote this out to add clarity for myself, as I did not understand the problem when I wrote the comment above. Here is my take on the problem

# Torrent basics
I'm pretty sure this is how a torrent client works:

1. A torrent is divided into a number of `pieces` (this is a universal definition). This is done at the time of torrent creation, and is afterwards fixed.
2. A `piece` is divided into a number of `chunks` (this is not a universal definition, but is common). This is done at runtime in the client. The torrent file specifies the length of the `piece` of interest -- this is the only relevant part of the torrent file when subdividing into chunks. Clients almost universally request 16 kB chunks, except possibly the last chunk of the last piece of the file. Clients that request larger chunks are typically ignored.
3. A leecher chooses a piece to download. It then iteratively requests each chunk of that piece. A request contains `(pieceIndex, start, length)`. To saturate their connection, they maintain a queue of 4-5 requests at a time.

Meanwhile, each client has two bits of information for each peer client:
1. `choked` -- will I send data to that peer?
2. `interested` -- Do I currently want data from that peer?

If Alice wants to tell Bob that she won't send data to him, she sends a `choke` message. If she changes her mind, and is willing to send data, she sends `unchoked`. Clients must choke most peers in order to not degrade TCP performance. It is usually kept below four. In the bittorrent protocol, choking messages are sent **every ten seconds.** It's not that choking/unchoking is inherently slow for some technical reason -- it's simply a choice made in the choking algorithm.

Likewise, if Bob knows that Alice has data that she wants, he sends `interested`. Once he's got all the data he wants from Alice, he sends `uninterested`.

# Payment thoughts

We've decided to use a simple payment channel to pay for data. This choice lets us completely separate payment transfer and data transfer.

We might later consider more exotic state channels, like the one discussed [here](https://github.com/statechannels/monorepo/issues/264#issuecomment-548359174).

# Problem

1. How do we decide when to choke a peer?
2. How do we decide when to pay a peer?

## Choking

Typically, Alice's client selects the four peers, among all peers interested in Alice, the four peers that currently have the best download rates _to Alice_. This needs to change: Alice only wants to unchoke peers that are paying her. 

## Paying

Typically, Bob's client sends requests to anyone that he's interested in who is not currently choking him. This needs to change: Bob only wants to send requests to people he intends to pay.

# Solutions
I've sketched out two ideas below
- [per-piece model](PLACEHOLDER)
- [balance model](PLACEHOLDER)

**Comment by spersico** [comment] 2019-11-01 15:34
Yesterday, with @joelalejandro, and with @andrewgordstewart's input, we discussed the issue, I've put them on writing [here](https://github.com/statechannels/monorepo/issues/324#issuecomment-548830995)

**Comment by junjizhi** [comment] 2020-03-04 21:15
@snario Can we move this issue to done in web3torrent project board?

**Comment by spersico** [comment] 2020-03-04 21:23
Sure!

**Closed by spersico** 2020-03-04 21:23 UTC
Labels: package: web3torrent, question
