### ISSUE TITLE
net::ERR_CONNECTION_REFUSED at http://localhost:3000/upload

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/monorepo#2132] opened 2020-06-10 19:20 UTC
https://app.circleci.com/pipelines/github/statechannels/monorepo/7254/workflows/45b7fce2-b632-40c3-ba2c-1157cf20c4f6/jobs/33328/steps

**Comment by lalexgap** [comment] 2020-06-11 22:39
I think this is a duplicate of #2079. It looks like `ganache` never properly started which caused the error.

**Closed** 2020-06-12 00:47 UTC
